name: Database Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  mysql:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sL https://raw.githubusercontent.com/datasherlocks/sherlock/main/install.sh |  sudo bash -s -- -b ./bin
      - name: Sync Database schema
        run: ./bin/sherlock register -c config/mysql.yaml --name employees
        env:
           DS_API_KEY: ${{ secrets.DS_API_KEY }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD_MYSQL }}
  postgres:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sL https://raw.githubusercontent.com/datasherlocks/sherlock/main/install.sh |  sudo bash -s -- -b bin
      - name: Sync Da tabase schema
        run: ./bin/sherlock register -c config/postgres.yaml --name store
        env:
           DS_API_KEY: ${{ secrets.DS_API_KEY }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD_POSTGRES }}
